### ISSUE TITLE
Demo tailwind 3 version, Smart select  & changing per page rows to 50 throwin error

### ISSUE THREAD

**Issue by BenOussama180** [LowerRockLabs/LaravelLivewireTablesAdvancedFilters#38]
when changed to 50 it throws error
![image](https://user-images.githubusercontent.com/81111919/224352420-f1a47151-bc67-476f-8f0a-1dcbaa95012c.png)

out of context question:  is it normal that the dropdown filter is hidden when the filters are too long, we cant see the end of it ,
and how can i do the integrated filter inside table such as name in the demo

**Comment by lrljoe** [comment]
Error should be remediated now, it was due to a conflict with the package expecting the defaults to be setup.

For inline filters, you just need to refer to the filter as a secondary header by it's key (typically this is the Str::slug of the name)
```php
            Column::make('Name')
                ->sortable(function (Builder $query, string $direction) {
                    return $query->orderBy('name', $direction); // Example, ->sortable() would work too.
                })
                ->searchable()
                ->secondaryHeader($this->getFilterByKey('name'))
                ->footer($this->getFilterByKey('name')),
```

You can also hide it from the menus if you do that by calling hiddenFromMenus() against the filter in question:
```php
            TextFilter::make('Email')
                ->hiddenFromMenus(),
```

Dropdown filter being hidden when it's too long - if you can give me a screenshot then I'll issue a fix.
